--- 

before_script: 
  - ./.travis/prepare.sh
  
language: php

php: 
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  
script: 
  - phpize
  - ./configure --with-cld2=libcld2
  - make
  - yes "s" | make test
  - sudo make install
